name: rs_tools
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Standard Libraries
  - numpy # Numerical Linear Algebra
  # - scipy # Scientific Computing
  # - scikit-image
  - xarray
  - rioxarray
  - goes2go
  - earthaccess
  - eumdac
  - pyinterp
  - satpy
  # - conda-forge::torchgeo
  - pandas # Data structure
  - scikit-learn # Machine Learning
  # - joblib # Parallelization
  # PLOTTING LIBRARY
  - matplotlib # standard plotting library
  - seaborn # Stats viz library
  # - conda-forge::hvplot
  # Storage
  - netCDF4
  - zarr
  - h5netcdf
  # - gdal>=3.4.1,<=3.6.3
  # - h5py
  # GUI
  - ipywidgets
  - ipykernel
  - tqdm
  - pip
  - pip:
      - toolz
      - typer
      - einops
      - cartopy
      - google-cloud-storage
      - xrpatcher
      # formatting
      - rasterio
      - black
      - pylint
      - isort
      - flake8
      - mypy
      - pytest
      - pre-commit
      # Notebook stuff
      - autoroot
      - pyprojroot
      - python-dotenv
      # logging
      - loguru
      # plotting
      - celluloid
      - corner
      - tabulate
      # experiment
      - hydra-core
      - hydra-zen
      # Docs
      - mkdocs-gen-files
      - mkdocs-literate-nav
      - mkdocs-git-authors-plugin
      - mkdocstrings
      - markdown-katex
      - pytkdocs
      - mdx-truly-sane-lists
      - mkdocs-jupyter
      - mkdocs-bibtex
      - pygments
      - mknotebooks
      - pymdown-extensions
      - mkdocs-material 
      - mkdocs
      - aiohttp
      # ITI
      - git+https://github.com/spaceml-org/InstrumentToInstrument.git@development
      - wandb
      
