name: rs_tools_ml
channels:
  - conda-forge
  # - pytorch
  # - nvidia
dependencies:
  - python=3.11
  # Standard Libraries
  - numpy # Numerical Linear Algebra
  - xarray
  - rioxarray
  - pandas # Data structure
  - scikit-image
  - scikit-learn # Machine Learning
  - geopandas
  - xarray
  - rioxarray
  - goes2go
  - earthaccess
  - eumdac
  - pyinterp
  - satpy
  - odc-geo
  - rasterio
  - pyresample
  # PLOTTING LIBRARY
  - matplotlib # standard plotting library
  - seaborn # Stats viz library
  - cartopy
  # Storage
  - h5py
  - zarr
  - netCDF4
  - zarr
  - h5netcdf
  # - nvidia/label/cuda-12.2.0::cuda
  # - pytorch-cuda
  # GUI
  - ipywidgets
  - ipykernel
  - tqdm
  - pip
  - pip:
      - toolz
      - typer
      - einops
      - einx
      - mlx-data
      # PYTORCH
      - torch>=1.8
      - torchvision
      - lightning
      - xrpatcher
      - torchgeo
      - georeader-spaceml
      # formatting
      - black
      - pylint
      - isort
      - flake8
      - mypy
      - pytest
      - pre-commit
      # Notebook stuff
      - autoroot
      - pyprojroot
      - python-dotenv
      # logging
      - loguru
      # plotting
      - celluloid
      - corner
      - tabulate
      # experiment
      - hydra-core
      - hydra-zen
      - wandb
      - xrpatcher
      - toolz
      - typer
      # experiment
      - hydra-core
      - hydra-zen
      # Docs
      - mkdocs-gen-files
      - mkdocs-literate-nav
      - mkdocs-git-authors-plugin
      - mkdocstrings
      - markdown-katex
      - pytkdocs
      - mdx-truly-sane-lists
      - mkdocs-jupyter
      - mkdocs-bibtex
      - pygments
      - mknotebooks
      - pymdown-extensions
      - mkdocs-material 
      - mkdocs
      - aiohttp
      # ITI
      - wandb
      
