download:
  _target_: rs_tools._src.data.goes.downloader_goes16.download
  save_dir: ${save_dir}/goes16/raw
  start_date: ${period.start_date}
  start_time: ${period.start_time}
  end_date: ${period.end_date}
  end_time: ${period.end_time}
  daily_window_t0: "13:00:00" # UTC - 1 to -3 
  daily_window_t1: "17:00:00"
  time_step: "1:00:00"

geoprocess:
  _target_: rs_tools._src.geoprocessing.goes.geoprocessor_goes16.geoprocess
  read_path: ${read_path}/goes16/raw
  save_path: ${save_path}/goes16/geoprocessed
  resolution: null
  region: "-45 0 -20 40"
  resample_method: null

# preprocess:

# patch:
#   _target_: rs_tools._src.preprocessing.prepatcher.prepatch
#   read_path: ${read_path}/goes16/geoprocessed
#   save_path: ${save_path}/goes16/analysis
#   patch_size: ${patch_size}
#   stride_size: ${stride_size}
#   nan_cutoff: ${nan_cutoff}
#   save_filetype: ${save_filetype}
