download:
  _target_: rs_tools._src.data.msg.downloader_msg_(modis_overpass).download
  save_dir: ${save_dir}
  start_date: ${period.start_date}
  start_time: ${period.start_time}
  end_date: ${period.end_date}
  end_time: ${period.end_time}

geoprocess:
  _target_: rs_tools._src.geoprocessing.msg.geoprocessor_msg.geoprocess
  read_path: ${read_path}/msg/raw
  save_path: ${save_path}/msg/geoprocessed
  resolution: null
  region: "-70 -15 20 5"
  resample_method: bilinear

# preprocess:

patch:
  _target_: rs_tools._src.preprocessing.prepatcher.prepatch
  read_path: ${read_path}/msg/geoprocessed
  save_path: ${save_path}/msg/analysis
  patch_size: ${patch_size}
  stride_size: ${stride_size}
  nan_cutoff: ${nan_cutoff}
  save_filetype: ${save_filetype}