# PATH WITH GEOPROCESSED DATA
read_path: /path/to/geoprocessed/data

# PATH FOR SAVING PATCHES
save_path: /path/to/save/patches

# PATCH PARAMETERS
patch_size: 256
stride_size: 256

# NAN CUTOFF
nan_cutoff: 0.5

# FILETYPE TO SAVE [nc = netcdf, tif = geotiff, np = numpy, npz = compressed numpy]
save_filetype: nc

defaults:
  - _self_